package com.harry.videowatermark.controller;

import cn.hutool.core.map.MapUtil;
import com.harry.videowatermark.common.TextUtil;
import com.harry.videowatermark.model.ApiResult;
import com.harry.videowatermark.model.VideoModel;
import com.harry.videowatermark.model.WaterOrder;
import com.harry.videowatermark.service.VideoService;
import com.harry.videowatermark.service.WaterOrderService;
import com.harry.videowatermark.service.WaterService;
import com.harry.videowatermark.service.impl.VideoFactory;
import com.harry.videowatermark.utils.AppVersion;
import com.harry.videowatermark.utils.MD5Util;
import javafx.util.Pair;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.util.Date;
import java.util.Map;

@Slf4j
@CrossOrigin
@RestController
@RequestMapping("/api/video")
public class VideoController {
    private static int OPEN = 102;
    private static final String MD5_SAFE = "watermarksafe";

    @Autowired
    private WaterOrderService waterOrderService;

    @Autowired
    private WaterService waterService;

    @RequestMapping("/open")
    public ApiResult getInfo(@RequestParam("open") boolean open, @RequestParam(value = "deviceId", required = false) String deviceId) {
        log.info("VideoController.getInfo,open= {}, OPEN={},deviceId={}", open, OPEN, deviceId);
        OPEN = open ? 102 : 100;
        if (deviceId != null) {
//            addDeviceId(deviceId);
        }
        return ApiResult.success(OPEN);
    }

    /**
     * 1.0以上
     *
     * @param version
     * @param deviceId
     * @param sign
     * @return
     */
    @RequestMapping("/info")
    public ApiResult info(@RequestParam("version") String version, @RequestParam("deviceId") String deviceId, @RequestParam("sign") String sign) {
        log.info("VideoController.info version= {} ,deviceId= {} ,sign={}", version, deviceId, sign);
        Map<String, Object> result = MapUtil.newHashMap(2);
        result.put("status", OPEN);
        try {
            if (!sign.equals(MD5Util.md5(deviceId, MD5_SAFE))) {
                log.warn("VideoController.warn sign version= {} ,deviceId= {} ,sign={}", version, deviceId, sign);
                return ApiResult.failed("签名错误");
            }
//        if (AppVersion.AUDIT_V.equals(version)) {
//            result.put("status", 100);
//        }
            result.put("limitTimes", waterService.incrementParseTimes(deviceId, version, 0) > 1);
            WaterOrder waterOrder = waterOrderService.getByDeviceId(deviceId);
            result.put("vipUser", false);
            if (waterOrder != null) {
                Date vipDate = waterOrder.getExpires_date_ms();
                result.put("vipUser", vipDate.after(new Date()));
                result.put("vipDate", vipDate.before(new Date()) ? "会员已过期" : "");
            } else if (OPEN == 102) {
                result.put("vipDate", "新用户免费试用三天，试用期间可随时取消订阅");
            }
            result.put("upgrade", Integer.parseInt(StringUtils.replace(version, ".", "")) < AppVersion.MAX_V);
        } catch (Exception e) {
            log.error("VideoController.info err", e);
        }
        return ApiResult.success(result);
    }

    /**
     * 1.0
     *
     * @param version
     * @param deviceId
     * @return
     */
    @RequestMapping("/getInfo")
    public ApiResult getInfo(@RequestParam("version") String version, @RequestParam("deviceId") String deviceId) {
        log.info("VideoController.getInfo version= {} ,deviceId= {}", version, deviceId);
        Map<String, Object> result = MapUtil.newHashMap(2);
        result.put("status", true);
        result.put("vipUser", true);
        return ApiResult.success(result);
    }

    private static Pair<String, String> LAST_URL = new Pair<>("", "");

    /**
     * 水印助手
     *
     * @param version
     * @param url
     * @param sign
     * @param source
     * @param deviceId
     * @return
     */
    @RequestMapping("/parse")
    public ApiResult parse(@RequestParam(value = "version", required = false) String version, @RequestParam("url") String url,
                           @RequestParam("sign") String sign, @RequestParam("source") String source, @RequestParam(value = "deviceId", required = false) String deviceId) {
        log.info("VideoController.parse,deviceId= {}, version={} source={},url={}, sign={},", deviceId, version, source, url, sign);
        try {
            String shortUrl = TextUtil.extractUrl(url);
            if (shortUrl == null) {
                return ApiResult.failed("请输入正确地址");
            }
            if (!sign.equals(MD5Util.md5(url, MD5_SAFE))) {
                return ApiResult.failed("签名错误");
            }
            if (LAST_URL != null && LAST_URL.getKey().equals(shortUrl)) {
                return ApiResult.success(new VideoModel(LAST_URL.getValue()));
            }
            WaterOrder waterOrder = waterOrderService.getByDeviceId(deviceId);
            if (waterOrder == null || waterOrder.getExpires_date_ms().before(new Date())) {
                if (waterService.incrementParseTimes(deviceId, version, 0) > 6) {
                    return ApiResult.failed("视频提取次数已用完,会员中心领取免费试用！");
                }
            }

            VideoService videoService = VideoFactory.getVideo(shortUrl);
            if (videoService != null) {
                VideoModel videoModel = videoService.parseUrl(shortUrl);
                waterService.addParseRecord(deviceId, version, shortUrl, videoModel != null);
                if (videoModel != null) {
                    waterService.incrementParseTimes(deviceId, version, 1);
                    LAST_URL = new Pair<>(shortUrl, videoModel.getPlayAddr());
                    return ApiResult.success(videoModel);
                } else {
                    return ApiResult.failed("视频链接异常");
                }
            } else {
                Integer type = waterService.vipUrlType(url, deviceId);
                if (type != null) {
                    return ApiResult.failed("已为您添加会员一" + (type == 0 ? "个月" : "年") + ",重新打开App生效");
                }
            }
            log.warn("VideoController.parse warn url= {} ,version={}", url, version);
            return ApiResult.failed("暂不支持改链接类型");
        } catch (Exception e) {
            log.error("VideoController.parse err deviceId={}, url={}, sign={},e={}", deviceId, url, sign, e);
        }
        return ApiResult.failed("");
    }

    /**
     * 猫咪之家
     *
     * @param url
     * @param source
     * @return
     */
    @RequestMapping("/parse/v2")
    public ApiResult parseV2(@RequestParam("url") String url, @RequestParam(value = "source", required = false) String source) {
        log.info("VideoController.parse err url={}, source={},", url, source);
        try {
            String shortUrl = TextUtil.extractUrl(url);
            if (shortUrl == null) {
                return ApiResult.failed("请输入正确地址");
            }

            VideoService videoService = VideoFactory.getVideo(shortUrl);
            if (videoService != null) {
                VideoModel videoModel = videoService.parseUrl(shortUrl);
                if (videoModel != null) {
                    return ApiResult.success(videoModel);
                } else {
                    return ApiResult.failed("视频链接异常");
                }
            }
            return ApiResult.failed("暂不支持改链接类型");
        } catch (Exception e) {
            log.error("VideoController.parse err url={}, source={},e={}", url, source, e);
        }
        return ApiResult.failed();
    }

    /**
     * 订单上报
     * @param version
     * @param sign
     * @param source
     * @param deviceId
     * @param receiptData
     * @return
     */
    @RequestMapping("/report")
    public ApiResult report(@RequestParam(value = "version") String version, @RequestParam(value = "sign") String sign,
                            @RequestParam(value = "source") String source, @RequestParam(value = "deviceId") String deviceId,
                            @RequestParam(value = "receiptData") String receiptData) {
        log.info("VideoController.report,deviceId= {}, version={} source={}, sign={},receiptData={}", deviceId, version, source, sign, receiptData);

        if (StringUtils.isBlank(deviceId) || StringUtils.isBlank(receiptData) || "nil".equals(receiptData)) {
            return ApiResult.failed("参数错误");
        }
        if (!sign.equals(MD5Util.md5(deviceId, MD5_SAFE))) {
            return ApiResult.failed("签名错误");
        }

        Map<String, Object> objectMap = MapUtil.newHashMap(1);
        objectMap.put("vipUser", waterOrderService.report(receiptData, deviceId));
        return ApiResult.success(objectMap);
    }

    public static void main(String[] args) throws IOException {
        String a = StringUtils.replace("1.1.4", ".", "");
        System.out.println(a);
        System.out.println(Integer.parseInt(a) < AppVersion.MAX_V);




//        String receipt = "MIIm4QYJKoZIhvcNAQcCoIIm0jCCJs4CAQExCzAJBgUrDgMCGgUAMIIWggYJKoZIhvcNAQcBoIIWcwSCFm8xghZrMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgEDAgEBBAMMATEwCwIBCwIBAQQDAgEAMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQoCAQEEBBYCNCswDAIBDgIBAQQEAgIAvTANAgENAgEBBAUCAwIjqDANAgETAgEBBAUMAzEuMDAOAgEJAgEBBAYCBFAyNTYwGAIBBAIBAgQQVgbV8+Ntdqf3idiSE5aE/jAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBsCAQICAQEEEwwRY29tLm13Yi53YXRlcm1hcmswHAIBBQIBAQQUwt4LZMVSST8gMBy+8/su8IYl0aQwHgIBDAIBAQQWFhQyMDIwLTEyLTA0VDExOjE2OjU0WjAeAgESAgEBBBYWFDIwMTMtMDgtMDFUMDc6MDA6MDBaME4CAQcCAQEERhcRu5k7n3gWGVWcm1FB0U0Uhek/Ybp6/Kf9v43gT+xDBNYp3RGGHjPWIljkkSWnXGHXX+JSEyNHgxiABCh+7b0M1zPbYYwwXwIBBgIBAQRXWqJXP/bITON8ZZiXWkjJEEBwuYiOtc6CP4JST408NQLu2q1G4lHUHJTQvCvRUIwpryshrTRv5Pa6gHQ4pICkcc2Yy3u7VLeZnjaF2Vm7amcVuJVVhQR/MIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1QWQwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTI6Mzk6NDBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1QWUwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDQyOTc4MTAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTI6Mzk6NTlaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTM6Mzk6NTlaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1SbgwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDQ2MzE2MDAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTM6Mzk6NTlaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTQ6Mzk6NTlaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1UZIwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDQ5NTgyMzAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTQ6Mzk6NTlaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTU6Mzk6NTlaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1WQcwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDUxODE1MTAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTU6Mzk6NTlaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTY6Mzk6NTlaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAyMBICAgavAgEBBAkCBwONfqg1YMcwGwICBqcCAQEEEgwQMTAwMDAwMDc0NDU0MDI1MTAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ0NDAyOTIzMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjBUMTY6Mzk6NTlaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjBUMTE6Mzk6NDJaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjBUMTc6Mzk6NTlaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4YCowGwICBqcCAQEEEgwQMTAwMDAwMDc0NzI4NzY4NjAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDQ6MTBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDk6MTBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4YGIwGwICBqcCAQEEEgwQMTAwMDAwMDc0NzI4OTc3MzAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTE6NTA6MTRaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTE6NTU6MTRaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4YWUwGwICBqcCAQEEEgwQMTAwMDAwMDc0NzI5NDAwNzAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTE6NTU6MzBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTI6MDA6MzBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4YiEwGwICBqcCAQEEEgwQMTAwMDAwMDc0NzI5NjUzNTAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTI6MDA6MzBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTI6MDU6MzBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4Yu4wGwICBqcCAQEEEgwQMTAwMDAwMDc0NzMwMDUwOTAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTI6MDU6MzBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTI6MTA6MzBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTA1MBICAgavAgEBBAkCBwONfqg7i4gwGwICBqcCAQEEEgwQMTAwMDAwMDc1MDIzNjE0OTAbAgIGqQIBAQQSDBAxMDAwMDAwNzUwMjM0ODQyMB8CAgaoAgEBBBYWFDIwMjAtMTItMDRUMTE6MTU6MTZaMB8CAgaqAgEBBBYWFDIwMjAtMTItMDRUMTE6MTE6MjRaMB8CAgasAgEBBBYWFDIwMjAtMTItMDRUMTE6MjA6MTZaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEBMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTAzMBICAgavAgEBBAkCBwONfqg4YCkwGwICBqcCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAbAgIGqQIBAQQSDBAxMDAwMDAwNzQ3Mjg3MTgyMB8CAgaoAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTBaMB8CAgaqAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDI6MTFaMB8CAgasAgEBBBYWFDIwMjAtMTEtMjdUMTE6NDQ6MTBaMIIBcAIBEQIBAQSCAWYxggFiMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEBMAwCAga3AgEBBAMCAQAwDgICBqYCAQEEBQwDMTA1MBICAgavAgEBBAkCBwONfqg7i4cwGwICBqcCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAbAgIGqQIBAQQSDBAxMDAwMDAwNzUwMjM0ODQyMB8CAgaoAgEBBBYWFDIwMjAtMTItMDRUMTE6MTE6MjNaMB8CAgaqAgEBBBYWFDIwMjAtMTItMDRUMTE6MTE6MjRaMB8CAgasAgEBBBYWFDIwMjAtMTItMDRUMTE6MTM6MjNaoIIOZTCCBXwwggRkoAMCAQICCA7rV4fnngmNMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE1MTExMzAyMTUwOVoXDTIzMDIwNzIxNDg0N1owgYkxNzA1BgNVBAMMLk1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKXPgf0looFb1oftI9ozHI7iI8ClxCbLPcaf7EoNVYb/pALXl8o5VG19f7JUGJ3ELFJxjmR7gs6JuknWCOW0iHHPP1tGLsbEHbgDqViiBD4heNXbt9COEo2DTFsqaDeTwvK9HsTSoQxKWFKrEuPt3R+YFZA1LcLMEsqNSIH3WHhUa+iMMTYfSgYMR1TzN5C4spKJfV+khUrhwJzguqS7gpdj9CuTwf0+b8rB9Typj1IawCUKdg7e/pn+/8Jr9VterHNRSQhWicxDkMyOgQLQoJe2XLGhaWmHkBBoJiY5uB0Qc7AKXcVz0N92O9gt2Yge4+wHz+KO0NP6JlWB7+IDSSMCAwEAAaOCAdcwggHTMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyMDQwHQYDVR0OBBYEFJGknPzEdrefoIr0TfWPNl3tKwSFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEeBgNVHSAEggEVMIIBETCCAQ0GCiqGSIb3Y2QFBgEwgf4wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYLAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAA2mG9MuPeNbKwduQpZs0+iMQzCCX+Bc0Y2+vQ+9GvwlktuMhcOAWd/j4tcuBRSsDdu2uP78NS58y60Xa45/H+R3ubFnlbQTXqYZhnb4WiCV52OMD3P86O3GH66Z+GVIXKDgKDrAEDctuaAEOR9zucgF/fLefxoqKm4rAfygIFzZ630npjP49ZjgvkTbsUxn/G4KT8niBqjSl/OnjmtRolqEdWXRFgRi48Ff9Qipz2jZkgDJwYyz+I0AZLpYYMB8r491ymm5WyrWHWhumEL1TKc3GZvMOxx6GUPzo22/SGAGDDaSK+zeGLUR2i0j0I78oGmcFxuegHs5R0UwYS/HE6gwggQiMIIDCqADAgECAggB3rzEOW2gEDANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwMjA3MjE0ODQ3WhcNMjMwMjA3MjE0ODQ3WjCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMo4VKbLVqrIJDlI6Yzu7F+4fyaRvDRTes58Y4Bhd2RepQcjtjn+UC0VVlhwLX7EbsFKhT4v8N6EGqFXya97GP9q+hUSSRUIGayq2yoy7ZZjaFIVPYyK7L9rGJXgA6wBfZcFZ84OhZU3au0Jtq5nzVFkn8Zc0bxXbmc1gHY2pIeBbjiP2CsVTnsl2Fq/ToPBjdKT1RpxtWCcnTNOVfkSWAyGuBYNweV3RY1QSLorLeSUheHoxJ3GaKWwo/xnfnC6AllLd0KRObn1zeFM78A7SIym5SFd/Wpqu6cWNWDS5q3zRinJ6MOL6XnAamFnFbLw/eVovGJfbs+Z3e8bY/6SZasCAwEAAaOBpjCBozAdBgNVHQ4EFgQUiCcXCam2GGCL7Ou69kdZxVJUo7cwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290LmNybDAOBgNVHQ8BAf8EBAMCAYYwEAYKKoZIhvdjZAYCAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAE/P71m+LPWybC+P7hOHMugFNahui33JaQy52Re8dyzUZ+L9mm06WVzfgwG9sq4qYXKxr83DRTCPo4MNzh1HtPGTiqN0m6TDmHKHOz6vRQuSVLkyu5AYU2sKThC22R1QbCGAColOV4xrWzw9pv3e9w0jHQtKJoc/upGSTKQZEhltV/V6WId7aIrkhoxK6+JJFKql3VUAqa67SzCu4aCxvCmA5gl35b40ogHKf9ziCuY7uLvsumKV8wVjQYLNDzsdTJWk26v5yZXpT+RN5yaZgem8+bQp0gF6ZuEujPYhisX4eOGBrr/TkJ2prfOv/TgalmcwHFGlXOxxioK0bA8MFR8wggS7MIIDo6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNjA0MjUyMTQwMzZaFw0zNTAyMDkyMTQwMzZaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnRymacJGsR0KO75Bsqwx+VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV/X5vyJQO6VY9NXQ3xZDUjFUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw+dPfMrSSgayP7OtbkO2V4c1ss9tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4++NwzeajTEV+H0xrUJZBicR0YgsQg0GHM4qBsTBY7FoEMoxos48d3mVz/2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAXowggF2MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjCCAREGA1UdIASCAQgwggEEMIIBAAYJKoZIhvdjZAUBMIHyMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wDQYJKoZIhvcNAQEFBQADggEBAFw2mUwteLftjJvc83eb8nbSdzBPwR+Fg4UbmT1HN/Kpm0COLNSxkBLYvvRzm+7SZA/LeU802KI++Xj/a8gH7H05g4tTINM4xLG/mk8Ka/8r/FmnBQl8F0BWER5007eLIztHo9VvJOLr0bdw3w9F4SfK8W147ee1Fxeo3H4iNcol1dkP1mvUoiQjEfehrI9zgWDGG1sJL5Ky+ERI8GA4nhX1PSZnIIozavcNgs/e66Mv+VNqW2TAYzN39zoHLFbr2g8hDtq6cxlPtdk2f8GHVdmnmbkyQvvY1XGefqFStxu9k0IkEirHDx22TZxeY8hLgBdQqorV2uT80AkHN7B1dSExggHLMIIBxwIBATCBozCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIDutXh+eeCY0wCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAQAhKLVO1t7nsPs7P20IuugEbdcdwKIXlLL4U2X2YL+AiEhY6V4ZGaY6FeIeIGp00KvpnMWuKJ6MHxQAA1eiZE403ttcbJr3ru0rZNWii5RXmrciz1LzBoN+XDD+UiKwJDAAS0QlaZ0utr4A+IFw4X1SkAwu7JUurVQNVu9ZGumTGAvd35R6HUgAtktehlaIBLpUurS6IIsQgv8eJIkVvenBvDfJmiBueebh9e4Jy2+TzT5pGjAhquM0TcaMpmLPHwq/WtgFhnCfop8DV0hMDFep061G/L5jAR8332rMlsPao2PxcxjM1hTA0tesaGtRWiWZ9d+dvEmkvv9PozS0nQvn";
//        String strin = "MIIuJgYJKoZIhvcNAQcCoIIuFzCCLhMCAQExCzAJBgUrDgMCGgUAMIIdxwYJKoZIhvcNAQcBoIIduASCHbQxgh2wMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgEDAgEBBAMMATEwCwIBCwIBAQQDAgEAMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQoCAQEEBBYCNCswDAIBDgIBAQQEAgIAvTANAgENAgEBBAUCAwIjqDANAgETAgEBBAUMAzEuMDAOAgEJAgEBBAYCBFAyNTYwGAIBBAIBAgQQVgbV8+Ntdqf3idiSE5aE/jAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBsCAQICAQEEEwwRY29tLm13Yi53YXRlcm1hcmswHAIBBQIBAQQUwt4LZMVSST8gMBy+8/su8IYl0aQwHgIBDAIBAQQWFhQyMDIwLTEyLTA1VDA1OjM3OjE5WjAeAgESAgEBBBYWFDIwMTMtMDgtMDFUMDc6MDA6MDBaMEkCAQcCAQEEQf7QbbOpTQgKxrUi9c95X8yP+E8wB0CFFjCk9CokDkK5Ap0K8FRFtJreBQPA8qbYVSIk0+LKro3lVoitiIS8HcgEMGUCAQYCAQEEXbl/ydDeBSv2seaR9l1M8ZUJPNWOQyV2oNtn/RaGIRsgFLPANbGQ1jGHf3vhCgw/cYjUFyHAG6Ejsy9n0Nzb0aidm+kNCBtvM3tLK7LmqpY4qXzVucXoCoHGqtU6ezCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNUFkMBsCAganAgEBBBIMEDEwMDAwMDA3NDQ0MDI5MjMwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDEyOjM5OjQwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNUFlMBsCAganAgEBBBIMEDEwMDAwMDA3NDQ0Mjk3ODEwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDEyOjM5OjU5WjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDEzOjM5OjU5WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNUm4MBsCAganAgEBBBIMEDEwMDAwMDA3NDQ0NjMxNjAwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDEzOjM5OjU5WjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDE0OjM5OjU5WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNVGSMBsCAganAgEBBBIMEDEwMDAwMDA3NDQ0OTU4MjMwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDE0OjM5OjU5WjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDE1OjM5OjU5WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNVkHMBsCAganAgEBBBIMEDEwMDAwMDA3NDQ1MTgxNTEwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDE1OjM5OjU5WjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDE2OjM5OjU5WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMjASAgIGrwIBAQQJAgcDjX6oNWDHMBsCAganAgEBBBIMEDEwMDAwMDA3NDQ1NDAyNTEwGwICBqkCAQEEEgwQMTAwMDAwMDc0NDQwMjkyMzAfAgIGqAIBAQQWFhQyMDIwLTExLTIwVDE2OjM5OjU5WjAfAgIGqgIBAQQWFhQyMDIwLTExLTIwVDExOjM5OjQyWjAfAgIGrAIBAQQWFhQyMDIwLTExLTIwVDE3OjM5OjU5WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGAqMBsCAganAgEBBBIMEDEwMDAwMDA3NDcyODc2ODYwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDExOjQ0OjEwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDExOjQ5OjEwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGBiMBsCAganAgEBBBIMEDEwMDAwMDA3NDcyODk3NzMwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDExOjUwOjE0WjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDExOjU1OjE0WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGFlMBsCAganAgEBBBIMEDEwMDAwMDA3NDcyOTQwMDcwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDExOjU1OjMwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDEyOjAwOjMwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGIhMBsCAganAgEBBBIMEDEwMDAwMDA3NDcyOTY1MzUwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDEyOjAwOjMwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDEyOjA1OjMwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGLuMBsCAganAgEBBBIMEDEwMDAwMDA3NDczMDA1MDkwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDEyOjA1OjMwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDEyOjEwOjMwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO4uIMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyMzYxNDkwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjE1OjE2WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjIwOjE2WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO4weMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyMzczMTkwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjIwOjE2WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjI1OjE2WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO4zEMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyMzkwOTIwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjI1OjE2WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjMwOjE2WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO41zMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyNDA3MjYwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjMwOjE2WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjM1OjE2WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO44xMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyNDI5ODQwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjM1OjE2WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjQwOjE2WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO47MMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyODU3MzUwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDEyOjUyOjU4WjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDEyOjU3OjU4WjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBATAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwMzASAgIGrwIBAQQJAgcDjX6oOGApMBsCAganAgEBBBIMEDEwMDAwMDA3NDcyODcxODIwGwICBqkCAQEEEgwQMTAwMDAwMDc0NzI4NzE4MjAfAgIGqAIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjEwWjAfAgIGqgIBAQQWFhQyMDIwLTExLTI3VDExOjQyOjExWjAfAgIGrAIBAQQWFhQyMDIwLTExLTI3VDExOjQ0OjEwWjCCAXACARECAQEEggFmMYIBYjALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBATAMAgIGtwIBAQQDAgEAMA4CAgamAgEBBAUMAzEwNTASAgIGrwIBAQQJAgcDjX6oO4uHMBsCAganAgEBBBIMEDEwMDAwMDA3NTAyMzQ4NDIwGwICBqkCAQEEEgwQMTAwMDAwMDc1MDIzNDg0MjAfAgIGqAIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjIzWjAfAgIGqgIBAQQWFhQyMDIwLTEyLTA0VDExOjExOjI0WjAfAgIGrAIBAQQWFhQyMDIwLTEyLTA0VDExOjEzOjIzWqCCDmUwggV8MIIEZKADAgECAggO61eH554JjTANBgkqhkiG9w0BAQUFADCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0xNTExMTMwMjE1MDlaFw0yMzAyMDcyMTQ4NDdaMIGJMTcwNQYDVQQDDC5NYWMgQXBwIFN0b3JlIGFuZCBpVHVuZXMgU3RvcmUgUmVjZWlwdCBTaWduaW5nMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQClz4H9JaKBW9aH7SPaMxyO4iPApcQmyz3Gn+xKDVWG/6QC15fKOVRtfX+yVBidxCxScY5ke4LOibpJ1gjltIhxzz9bRi7GxB24A6lYogQ+IXjV27fQjhKNg0xbKmg3k8LyvR7E0qEMSlhSqxLj7d0fmBWQNS3CzBLKjUiB91h4VGvojDE2H0oGDEdU8zeQuLKSiX1fpIVK4cCc4Lqku4KXY/Qrk8H9Pm/KwfU8qY9SGsAlCnYO3v6Z/v/Ca/VbXqxzUUkIVonMQ5DMjoEC0KCXtlyxoWlph5AQaCYmObgdEHOwCl3Fc9DfdjvYLdmIHuPsB8/ijtDT+iZVge/iA0kjAgMBAAGjggHXMIIB0zA/BggrBgEFBQcBAQQzMDEwLwYIKwYBBQUHMAGGI2h0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtd3dkcjA0MB0GA1UdDgQWBBSRpJz8xHa3n6CK9E31jzZd7SsEhTAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFIgnFwmpthhgi+zruvZHWcVSVKO3MIIBHgYDVR0gBIIBFTCCAREwggENBgoqhkiG92NkBQYBMIH+MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wDgYDVR0PAQH/BAQDAgeAMBAGCiqGSIb3Y2QGCwEEAgUAMA0GCSqGSIb3DQEBBQUAA4IBAQANphvTLj3jWysHbkKWbNPojEMwgl/gXNGNvr0PvRr8JZLbjIXDgFnf4+LXLgUUrA3btrj+/DUufMutF2uOfx/kd7mxZ5W0E16mGYZ2+FogledjjA9z/Ojtxh+umfhlSFyg4Cg6wBA3LbmgBDkfc7nIBf3y3n8aKipuKwH8oCBc2et9J6Yz+PWY4L5E27FMZ/xuCk/J4gao0pfzp45rUaJahHVl0RYEYuPBX/UIqc9o2ZIAycGMs/iNAGS6WGDAfK+PdcppuVsq1h1obphC9UynNxmbzDscehlD86Ntv0hgBgw2kivs3hi1EdotI9CO/KBpnBcbnoB7OUdFMGEvxxOoMIIEIjCCAwqgAwIBAgIIAd68xDltoBAwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTEzMDIwNzIxNDg0N1oXDTIzMDIwNzIxNDg0N1owgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKOFSmy1aqyCQ5SOmM7uxfuH8mkbw0U3rOfGOAYXdkXqUHI7Y5/lAtFVZYcC1+xG7BSoU+L/DehBqhV8mvexj/avoVEkkVCBmsqtsqMu2WY2hSFT2Miuy/axiV4AOsAX2XBWfODoWVN2rtCbauZ81RZJ/GXNG8V25nNYB2NqSHgW44j9grFU57Jdhav06DwY3Sk9UacbVgnJ0zTlX5ElgMhrgWDcHld0WNUEi6Ky3klIXh6MSdxmilsKP8Z35wugJZS3dCkTm59c3hTO/AO0iMpuUhXf1qarunFjVg0uat80YpyejDi+l5wGphZxWy8P3laLxiX27Pmd3vG2P+kmWrAgMBAAGjgaYwgaMwHQYDVR0OBBYEFIgnFwmpthhgi+zruvZHWcVSVKO3MA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUK9BpR5R2Cf70a40uQKb3R01/CF4wLgYDVR0fBCcwJTAjoCGgH4YdaHR0cDovL2NybC5hcHBsZS5jb20vcm9vdC5jcmwwDgYDVR0PAQH/BAQDAgGGMBAGCiqGSIb3Y2QGAgEEAgUAMA0GCSqGSIb3DQEBBQUAA4IBAQBPz+9Zviz1smwvj+4ThzLoBTWobot9yWkMudkXvHcs1Gfi/ZptOllc34MBvbKuKmFysa/Nw0Uwj6ODDc4dR7Txk4qjdJukw5hyhzs+r0ULklS5MruQGFNrCk4QttkdUGwhgAqJTleMa1s8Pab93vcNIx0LSiaHP7qRkkykGRIZbVf1eliHe2iK5IaMSuviSRSqpd1VAKmuu0swruGgsbwpgOYJd+W+NKIByn/c4grmO7i77LpilfMFY0GCzQ87HUyVpNur+cmV6U/kTecmmYHpvPm0KdIBembhLoz2IYrF+Hjhga6/05Cdqa3zr/04GpZnMBxRpVzscYqCtGwPDBUfMIIEuzCCA6OgAwIBAgIBAjANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMDYwNDI1MjE0MDM2WhcNMzUwMjA5MjE0MDM2WjBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkkakJH5HbHkdQ6wXtXnmELes2oldMVeyLGYne+Uts9QerIjAC6Bg++FAJ039BqJj50cpmnCRrEdCju+QbKsMflZ56DKRHi1vUFjczy8QPTc4UadHJGXL1XQ7Vf1+b8iUDulWPTV0N8WQ1IxVLFVkds5T39pyez1C6wVhQZ48ItCD3y6wsIG9wtj8BMIy3Q88PnT3zK0koGsj+zrW5DtleHNbLPbU6rfQPDgCSC7EhFi501TwN22IWq6NxkkdTVcGvL0Gz+PvjcM3mo0xFfh9Ma1CWQYnEdGILEINBhzOKgbEwWOxaBDKMaLOPHd5lc/9nXmW8Sdh2nzMUZaF3lMktAgMBAAGjggF6MIIBdjAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUK9BpR5R2Cf70a40uQKb3R01/CF4wHwYDVR0jBBgwFoAUK9BpR5R2Cf70a40uQKb3R01/CF4wggERBgNVHSAEggEIMIIBBDCCAQAGCSqGSIb3Y2QFATCB8jAqBggrBgEFBQcCARYeaHR0cHM6Ly93d3cuYXBwbGUuY29tL2FwcGxlY2EvMIHDBggrBgEFBQcCAjCBthqBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMA0GCSqGSIb3DQEBBQUAA4IBAQBcNplMLXi37Yyb3PN3m/J20ncwT8EfhYOFG5k9RzfyqZtAjizUsZAS2L70c5vu0mQPy3lPNNiiPvl4/2vIB+x9OYOLUyDTOMSxv5pPCmv/K/xZpwUJfBdAVhEedNO3iyM7R6PVbyTi69G3cN8PReEnyvFteO3ntRcXqNx+IjXKJdXZD9Zr1KIkIxH3oayPc4FgxhtbCS+SsvhESPBgOJ4V9T0mZyCKM2r3DYLP3uujL/lTaltkwGMzd/c6ByxW69oPIQ7aunMZT7XZNn/Bh1XZp5m5MkL72NVxnn6hUrcbvZNCJBIqxw8dtk2cXmPIS4AXUKqK1drk/NAJBzewdXUhMYIByzCCAccCAQEwgaMwgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkCCA7rV4fnngmNMAkGBSsOAwIaBQAwDQYJKoZIhvcNAQEBBQAEggEAmxB3Wo2VcmInCpow8MgJc00k5M3QDTymiI6AYuSOC/u1IiPMOL1HDKIiw4TaAQgyZJajrRzPSdabVTBuoRZQohhLo6R2hz4LRZqU/03aKY26eEJobSJ8++xWzS14OkMoPzn1iAkLAfv+25/03AuNwdaAcjzqvYU6XfKsCpeYgKPiRah3LS2F3xQfkPS2SN4tNob8H9x4em1XhTf4ulQfr8+1621a5flSnvfryVRs9RYINodIoJMZddiJZpi3EUNopBfr72WW9xzImCgKaNghy9CYlT0zC0gaYkJEhGOzk7bLXe7dv9BrMxG2+PMi8Iv7Wqu33pZfqRmgrRpN3xnZ9A==";
//        String url = "https://sandbox.itunes.apple.com/verifyReceipt";
//        String url1 = "https://buy.itunes.apple.com/verifyReceipt";
//        String psw = "b67f1cf086ff4b569f9ffc2102e3c5df";
//        String rep = HttpUtil.post(url, "{\"receipt-data\":\"" + strin + "\", \"password\":\"" + psw + "\"}");
//        System.out.println(rep);
//        JSONObject object = JSONObject.parseObject(rep);
//        System.out.println(object.getString("latest_receipt"));

//        String verifyResult = IosVerifyUtil.buyAppVerify(receipt, 0);

//        System.out.println(object.getJSONArray("latest_receipt_info"));

//        String body = "deviceId=AB65BAD4-F3C7-417C-A61A-81E174B5094E&receiptData=nil&sign=f2ae62046f56c43da0bf99acb6c7d8c1&source=watermark&version1=Optional%28%221.1.1%22%29\n";
//
//        System.out.println("FAF747A3-25BE-4849-A1AA-D95F881033DB".length());
//
//        long start = System.currentTimeMillis();
//        String str = HttpUtil.get("https://ip.sanv.org/index.php?ip=124.126.229.82", 1100);
//        if (str.contains("China")) {
//            System.out.println("China");
//        } else {
//            System.out.println("---China");
//        }
//        System.out.println(System.currentTimeMillis() - start);
    }

}
